trigger:
- main

pool:
  name: Default

variables:
- group: terraform-secrets

steps:

# Step 1: Build Docker Image
- script: |
    docker build -t devops-app .
  displayName: 'Build Docker Image'

# Step 2: Azure Login (Service Principal)
- script: |
    az login --service-principal \
      -u $(ARM_CLIENT_ID) \
      -p $(ARM_CLIENT_SECRET) \
      --tenant $(ARM_TENANT_ID)
  displayName: 'Azure Login'

# Step 3: Login to ACR
- script: |
    az acr login --name sachindevops
  displayName: 'Login to ACR'

# Step 4: Tag Docker Image
- script: |
    docker tag devops-app sachindevops.azurecr.io/devops-app:v1
  displayName: 'Tag Docker Image'

# Step 5: Push Docker Image to ACR
- script: |
    docker push sachindevops.azurecr.io/devops-app:v1
  displayName: 'Push Docker Image'
